### ISSUE TITLE
BK doesn't work correctly on rotation

### ISSUE THREAD

**Issue by thakkarparth007** [sam09/LogoJS#1]
Give:
FW 100
LT 45
FW 50
BK 50

The output is incorrect. BK doesn't go backward, and instead goes in some other direction.

**Comment by thakkarparth007** [comment]
I just went through the code. Instead of maintaining an angle variable, why don't you just rotate the canvas using `context.rotate( <angle> )`?

**Comment by sam09** [comment]
Thanks for the suggestion.. Will work on it
